name: Auto Increment and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Calculate new version tag
        id: new_tag
        run: |
          # Get the latest tag, if no tags are found, start with v1.0.0
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null) || latest_tag="v1.0.0"
          echo "Latest tag: $latest_tag"

          if [ "$latest_tag" == "v1.0.0" ]; then
            new_tag=$latest_tag
          else
            # Increment the patch version
            IFS='.' read -ra VERSION <<< "${latest_tag#v}"
            ((VERSION[2]++))
            new_tag="v${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"
          fi
          echo "New tag: $new_tag"

          # Set output
          echo "::set-output name=tag::$new_tag"

      - name: Create and push new tag
        run: |
          new_tag=${{ steps.new_tag.outputs.tag }}
          git tag $new_tag
          git push https://rajvaya:${{ secrets.NEW_PAT }}@github.com/rajvaya/aisplash-dist.git $new_tag


      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_PAT }}
        with:
          tag_name: ${{ steps.new_tag.outputs.tag }}
          release_name: Release ${{ steps.new_tag.outputs.tag }}
          body: 'New release ${{ steps.new_tag.outputs.tag }}'
          draft: false
          prerelease: false
